// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcy9LoUSBVm3Rd29zxxJ8-cHXOaPEio7A',
    appId: '1:817841211182:web:06104b038ae5c89bfe9cbf',
    messagingSenderId: '817841211182',
    projectId: 'medimateapp-400f6',
    authDomain: 'medimateapp-400f6.firebaseapp.com',
    storageBucket: 'medimateapp-400f6.firebasestorage.app',
    measurementId: 'G-M7XTFMK7BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTF6NKJ4GYEFPzbKQpceMnFJzk71LecJs',
    appId: '1:817841211182:android:db871730c0c5baa5fe9cbf',
    messagingSenderId: '817841211182',
    projectId: 'medimateapp-400f6',
    storageBucket: 'medimateapp-400f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoT7gf-jLrKidRSUsAWV5wkZasLE0XufQ',
    appId: '1:817841211182:ios:6dfc68dcd49fc3aefe9cbf',
    messagingSenderId: '817841211182',
    projectId: 'medimateapp-400f6',
    storageBucket: 'medimateapp-400f6.firebasestorage.app',
    iosBundleId: 'com.example.medimateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoT7gf-jLrKidRSUsAWV5wkZasLE0XufQ',
    appId: '1:817841211182:ios:6dfc68dcd49fc3aefe9cbf',
    messagingSenderId: '817841211182',
    projectId: 'medimateapp-400f6',
    storageBucket: 'medimateapp-400f6.firebasestorage.app',
    iosBundleId: 'com.example.medimateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcy9LoUSBVm3Rd29zxxJ8-cHXOaPEio7A',
    appId: '1:817841211182:web:b02c773168fe35d9fe9cbf',
    messagingSenderId: '817841211182',
    projectId: 'medimateapp-400f6',
    authDomain: 'medimateapp-400f6.firebaseapp.com',
    storageBucket: 'medimateapp-400f6.firebasestorage.app',
    measurementId: 'G-PSJVRL9FFB',
  );
}
